package com.rinf.bringx.ViewModels;

public enum MEETING_STATUS { PENDING, PICKUP_DRIVING, PICKUP_ARRIVED, PICKUP_DONE, DELIVERY_DRIVING, DELIVERY_ARRIVED, DELIVERY_DONE, PICKUP_REJECTED, PICKUP_FAILED, DELIVERY_REJECTED, DELIVERY_FAILED};
